name: Setup for validate workflow
description: Reusable steps for validation jobs
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: lts/iron
    - uses: pnpm/action-setup@v4

    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm i --frozen-lockfile
      shell: bash
