name: Validate pushes to main and all PRs
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/validate-setup
      - name: Setup e2e tests
        run: pnpm --filter=remix-testing-lab exec playwright install --with-deps

      - name: Validate project
        run: pnpm exec turbo run lint typecheck e2e --no-cache

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: remix-testing-lab/playwright-report/
          retention-days: 30
